#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Release

#Toolchain
CC := C:/SysGCC/Beaglebone/bin/arm-angstrom-linux-gnueabi-gcc.exe
CXX := C:/SysGCC/Beaglebone/bin/arm-angstrom-linux-gnueabi-g++.exe
LD := $(CXX)
AR := C:/SysGCC/Beaglebone/bin/arm-angstrom-linux-gnueabi-ar.exe
OBJCOPY := C:/SysGCC/Beaglebone/bin/arm-angstrom-linux-gnueabi-objcopy.exe

#Additional flags
PREPROCESSOR_MACROS := NDEBUG RELEASE
INCLUDE_DIRS := ../libraries/live555/live_media/liveMedia/include ../libraries/live555/live_media/groupsock/include ../libraries/live555/live_media/BasicUsageEnvironment/include ../libraries/live555/live_media/UsageEnvironment/include ../libuvxx/include
LIBRARY_DIRS := 
LIBRARY_NAMES := 
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O3
CXXFLAGS := -ggdb -ffunction-sections -O3
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 
LINKER_SCRIPT := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
USE_DEL_TO_CLEAN := 1
CP_NOT_AVAILABLE := 1
IS_LINUX_PROJECT := 1
